name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [26, 24, 22]
        axios:
          - '^1'

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.5.13/install-safe-chain.sh | sh -s -- --ci

      - name: Install Packages
        run: npm install

      - name: Install fixed axios
        run: npm install -D 'axios@${{ matrix.axios }}'

      - name: Lint
        run: npm run lint

      # Dirty hacks for https://github.com/mpyw/axios-case-converter/issues/47
      - name: Disable dirty hacks for old version
        if: ${{ matrix.axios == '^0' }}
        run: |
          cat <<EOD > test/axios-headers-dirty-hacks.ts
          export function newAxiosHeadersFrom(thing?: Record<string, string | string[] | number | boolean | null>): Record<string, string | string[] | number | boolean | null> {
            return thing ?? {}
          }
          EOD

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Test ESM Import
        run: npm run test:esm

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node:${{ matrix.node }} axios:${{ matrix.axios }}
          parallel: true

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
