name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [26, 24, 22]
        axios:
          - '^1'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.5.13/install-safe-chain.sh | sh -s -- --ci

      - name: Install Packages
        run: npm install

      - name: Install fixed axios
        run: npm install -D 'axios@${{ matrix.axios }}'

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run check

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Test ESM Import
        run: npm run test:esm

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node:${{ matrix.node }} axios:${{ matrix.axios }}
          parallel: true

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
